# message that a player sees when he is not in the list of allowed players
denied_message: " you are not on the list of allowed players on this server "
# message about successful reload
reload_message: " Magic Penatration reloaded successfully "
# message when a player tries to enter a command without permission
no_permision_message: " Sorry, but you do not have permission to run this command. "
# message when a player is added to the list of allowed players
added_player_message: " added to the list of eligible players "
# message when a player removes a player from the list of allowed players
delete_message: " removed from the list of eligible players "
# message when a player is not found in the list of allowed players
player_not_found_message: " not found in the list of allowed players "
# message when the list of allowed players is empty
empty_list_message: " the list of allowed players is empty "
# message when the player types the command /penetration list
players_in_list: " players on the eligible players list: "
